### ISSUE TITLE
Figure out how to autodetect correct input terminal id and processing terminal id

### ISSUE THREAD

**Issue by makenai** [makenai/node-uvc-control#1] opened 2016-05-10 02:11 UTC
I'm not sure how to do this in libusb See this section of the documentation for details:

https://github.com/makenai/node-uvc-control#note-on-inputterminalid--processingunitid

**Comment by positlabs** [comment] 2017-06-19 02:49
Just realized that i created a duplicate of this. Since the initial comment in mine is more verbose, I'm going to track it there. #14

**Closed as completed by positlabs** 2017-06-19 02:49 UTC
